### ISSUE TITLE
Please add a screen shot and a `.plugin.zsh` file

### ISSUE THREAD

**Issue by unixorn** [eikendev/turs#2]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, if you put the code the readme says to add for `.zshrc` into `turs.plugin.zsh`, most framework managers will automatically load it without the user needing to edit `.zshrc`.

Thanks!

**Comment by eikendev** [comment]
Thanks for consideration, done! :blush:
